# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MH <- function(lastMean, estimatedRandomEffects, y, N, randomEffectSamp, eta, i, popInd, invcov, accept, iter, rate, unifs) {
    invisible(.Call('flowReMix_MH', PACKAGE = 'flowReMix', lastMean, estimatedRandomEffects, y, N, randomEffectSamp, eta, i, popInd, invcov, accept, iter, rate, unifs))
}

zero <- function(accept) {
    .Call('flowReMix_zero', PACKAGE = 'flowReMix', accept)
}

