# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MH <- function(lastMean, estimatedRandomEffects, y, N, randomEffectSamp, i, popInd, invcov, accept, iter, rate, unifs, nullEta, altEta) {
    invisible(.Call('flowReMix_MH', PACKAGE = 'flowReMix', lastMean, estimatedRandomEffects, y, N, randomEffectSamp, i, popInd, invcov, accept, iter, rate, unifs, nullEta, altEta))
}

zero <- function(accept) {
    .Call('flowReMix_zero', PACKAGE = 'flowReMix', accept)
}

