# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MH <- function(randomSampList, lastMean, estimatedRandomEffects, y, N, randomEffectSamp, eta, i, popInd, invcov, accept, iter, rate) {
    invisible(.Call('flowReMix_MH', PACKAGE = 'flowReMix', randomSampList, lastMean, estimatedRandomEffects, y, N, randomEffectSamp, eta, i, popInd, invcov, accept, iter, rate))
}

